### PR TITLE
feat(ci): [TG-271] npm publish

### PR DESCRIPTION
**Pull request by borys-ihnatyev**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/garage-it/SmartHouse-broker/pull/5" target="_blank">ReviewNinja

**Comment by disist** [comment]
Why build is failed?

**Comment by borys-ihnatyev** [comment]
@disist, I am not sure why, and I would appreciate your help much.

**Comment by disist** [comment]
@borys-ihnatyev 
Helped out 👍 

PS: By this article https://sudogem.wordpress.com/2016/06/14/travis-ci-this-version-of-nodenanv8-requires-a-c11-compiler/

**Comment by borys-ihnatyev** [comment]
@disist Thanx a lot

**Pull request merged**
